clone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
]


urlpatterns += [
    path("", include("quena.urls", namespace="quena")),
    path("user/", include("user.urls", namespace="user")),
]

quena/urls.py
from . import views
from django.urls import path

app_name = "quena"
urlpatterns = [
    path("", views.TodayQuestionListView.as_view(), name="index"),
    path("ask/", views.QuestionCreateView.as_view(), name="ask"),
    path("question/<int:pk>/", views.QuestionDetailView.as_view(), name="question_detail"),
    path("question/<int:pk>/answer/", views.AnswerCreateView.as_view(), name="answer_question"),
    path("answer/<int:pk>/accept/", views.UpdateAnswerAcceptanceView.as_view(), name="update_answer_acceptance"),
    path("daily_questions/<int:year>/<int:month>/<int:day>/", views.DailyQuestionListView.as_view(), name="daily_questions"),
    path("question/search/", views.SearchView.as_view(), name="question_search"),
]

user/urls.py
from . import views
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

app_name = "user"
urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", views.UserRegisterView.as_view(), name="register"),
]

quena/models.py
from django.db import models
from django.conf import settings
from django.urls.base import reverse
from .service import elasticsearch

class Question(models.Model):
    title = models.CharField(max_length=140)
    question = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("quena:question_detail", kwargs={"pk": self.id})
    
    def can_accept_answers(self, user):
        return user == self.user
    
    def as_elasticsearch_dict(self):
        return {
            "_id": self.id,
            "_type": "doc",
            "text": "{}\n{}".format(self.title, self.question),
            "question_body": self.question,
            "title": self.title,
            "id": self.id,
            "created": self.created,
        }
    
    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        super().save(force_insert=force_insert,
                    force_update=force_update,
                    using=using,
                    update_fields=update_fields)
        elasticsearch.upsert(self)


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    accepted = models.BooleanField(default=False)

    class Meta:
        ordering = "-created",
    
    def __str__(self):
        return self.question.title

quena/forms.py
from .models import Question, Answer
from django import forms
from django.contrib.auth import get_user_model


class QuestionForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True,
    )

    class Meta:
        model = Question
        fields = "title", "question", "user",


class AnswerForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=False,
    )

    question = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=Question.objects.all(),
        disabled=True,
    )

    class Meta:
        model = Answer
        fields = "answer", "user", "question",


class AnswerAcceptanceForm(forms.ModelForm):
    accepted = forms.BooleanField(
        widget=forms.HiddenInput,
        required=False,
    )

    class Meta:
        model = Answer
        fields = "accepted",

quena/views.py
from .models import Question, Answer
from .forms import QuestionForm, AnswerForm, AnswerAcceptanceForm
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.views.generic.dates import DayArchiveView
from django.views.generic.base import RedirectView
from django.views.generic.base import TemplateView
from django.http import HttpResponseBadRequest, HttpResponseRedirect
from django.utils import timezone
from django.urls.base import reverse
from .service.elasticsearch import search_for_questions


class QuestionCreateView(LoginRequiredMixin, CreateView):
    form_class = QuestionForm
    template_name = "quena/ask.html"

    def get_initial(self):
        return {
            "user": self.request.user.id,
        }
    
    def form_valid(self, form):
        action = self.request.POST.get("action")
        if action == "SAVE":
            return super().form_valid(form)
        elif action == "PREVIEW":
            preview = Question(
                question = form.cleaned_data["question"],
                title = form.cleaned_data["title"],
            )
            ctx = self.get_context_data(preview=preview)
            return self.render_to_response(context=ctx)
        return HttpResponseBadRequest


class QuestionDetailView(DetailView):
    model = Question

    ACCEPT_FORM = AnswerAcceptanceForm(initial={"accepted": True})
    REJECT_FORM = AnswerAcceptanceForm(initial={"accepted": False})

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx.update({
            "answer_form": AnswerForm(initial={
                "user": self.request.user.id,
                "question": self.object.id,
            })
        })

        if self.object.can_accept_answers(self.request.user):
            ctx.update({
                "accept_form": self.ACCEPT_FORM,
                "reject_form": self.REJECT_FORM,
            })
        return ctx


class AnswerCreateView(LoginRequiredMixin, CreateView):
    form_class = AnswerForm
    template_name = "quena/create_answer.html"

    def get_initial(self):
        return {
            "question": self.get_question().id,
            "user": self.request.user.id,
        }
    
    def get_context_data(self, **kwargs):
        return super().get_context_data(question=self.get_question(), **kwargs)
    
    def get_success_url(self):
        return self.object.question.get_absolute_url()
    
    def form_valid(self, form):
        action = self.request.POST.get("action")
        if action == 'SAVE':
            return super().form_valid(form)
        elif action == "PREVIEW":
            ctx = self.get_context_data(preview=form.cleaned_data["answer"])
            return self.render_to_response(context=ctx)
        return HttpResponseBadRequest()
    
    def get_question(self):
        return Question.objects.get(pk=self.kwargs["pk"])


class UpdateAnswerAcceptanceView(LoginRequiredMixin, UpdateView):
    form_class = AnswerAcceptanceForm
    queryset = Answer.objects.all()

    def get_success_url(self):
        return self.object.question.get_absolute_url()
    
    def form_valid(self, form):
        action = self.request.POST.get("action")
        if action == "REJECT":
            self.object.accepted = False
            self.object.save()
            return HttpResponseRedirect(redirect_to=self.object.question.get_absolute_url())
        elif action == "ACCEPT":
            self.object.accepted = True
            self.object.save()
            return HttpResponseRedirect(redirect_to=self.object.question.get_absolute_url())


class DailyQuestionListView(DayArchiveView):
    queryset = Question.objects.all()
    date_field = "created"
    month_format = "%m"
    allow_empty = True


class TodayQuestionListView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        today = timezone.now()
        return reverse("quena:daily_questions",
            kwargs={
                "day": today.day,
                "month": today.month,
                "year": today.year,
            }
        )


class SearchView(TemplateView):
    template_name = "quena/search.html"

    def get_context_data(self, **kwargs):
        query = self.request.GET.get("question", None)
        ctx = super().get_context_data(query=query, **kwargs)
        if query:
            results = search_for_questions(query)
            ctx["hits"] = results
        return ctx

quena/templates/quena/snippet/display_question.html
{% load markdownify %}
<div class="question">
    <div class="meta col-sm-12">
        <h1>{{question.title}}</h1>
        <p>Asked by <strong>{{question.user}}</strong> on {{question.created}}</p>
    </div>
    <div class="body col-sm-12">
        {{question.question|markdownify}}
    </div>
</div>

quena/templates/quena/snippet/list_answers.html
{% load markdownify %}
<h3>Answers</h3>
<ul class="list-unstyled answers">
    {% for answer in question.answer_set.all %}
        <li class="answer row">
            <div class="col-sm-9 col-md-10">
                <div class="body">{{answer.answer|markdownify}}</div>
                <div class="meta font-weight-light">
                    <p>Answered by {{answer.user}} on {{answer.created}}</p>
                </div>
            </div>
            <div class="col-sm-3 col-md-2 text-center">
                {% if answer.accepted %}
                    <span class="badge badge-pill badge-success">Accepted</span>
                {% endif %}
                {% if answer.accepted and reject_form %}
                    <form method="POST" action="{% url 'quena:update_answer_acceptance' answer.pk %}">
                        {% csrf_token %}
                        {{reject_form}}
                        <button type="submit" class="btn btn-danger btn-sm" name="action" value="REJECT">
                            <i class="fa fa-times" aria-hidden="true"></i>Reject
                        </button>
                    </form>
                {% elif accept_form %}
                    <form method="POST" action="{% url 'quena:update_answer_acceptance' answer.pk %}">
                        {% csrf_token %}
                        {{accept_form}}
                        <button type="submit" class="btn btn-success" name="action" value="ACCEPT">
                            <i class="fa fa-check-circle" aria-hidden="true"></i>Accept
                        </button>
                    </form>
                {% endif %}
            </div>
        </li>
    {% empty %}
        <li class="answer">No answers yet!</li>
    {% endfor %}
</ul>

quena/templates/quena/snippet/post_answer.html
{% load crispy_forms_tags %}
<div class="col-sm-12">
    <h3>Post your answer</h3>
    <form method="POST" action="{% url 'quena:answer_question' question.id %}">
        {% csrf_token %}
        {{answer_form|crispy}}
        <button class="btn btn-primary" type="submit" name="action" value="PREVIEW">Preview</button>
        <button class="btn btn-success" type="submit" name="action" value="SAVE">Save</button>
    </form>
</div>