clone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
]


urlpatterns += [
    path("", include("quena.urls", namespace="quena")),
    path("user/", include("user.urls", namespace="user")),
]

quena/urls.py
from . import views
from django.urls import path

app_name = "quena"
urlpatterns = [
    path("", views.TodayQuestionListView.as_view(), name="index"),
    path("ask/", views.QuestionCreateView.as_view(), name="ask"),
    path("question/<int:pk>/", views.QuestionDetailView.as_view(), name="question_detail"),
    path("question/<int:pk>/answer/", views.AnswerCreateView.as_view(), name="answer_question"),
    path("answer/<int:pk>/accept/", views.UpdateAnswerAcceptanceView.as_view(), name="update_answer_acceptance"),
    path("daily_questions/<int:year>/<int:month>/<int:day>/", views.DailyQuestionListView.as_view(), name="daily_questions"),
    path("question/search/", views.SearchView.as_view(), name="question_search"),
]

user/urls.py
from . import views
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

app_name = "user"
urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", views.UserRegisterView.as_view(), name="register"),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title%}Quena{% endblock title%}</title>
        <link rel="stylesheet" href="{%static 'css/base.css' %}">
        <link rel="stylesheet" href="{% static 'css/boot.min.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container">
                <a class="navbar-brand" href="/">QUENA</a>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'quena:ask' %}">Ask</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'quena:index' %}">Today's Questions</a>
                    </li>
                    {% if user.is_authenticated %}
                    <span class="navbar-text">({{user.username}})</span>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user:logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user:login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user:register' %}">Register</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <form class="form-inline" action="{% url 'quena:question_search' %}" method="GET">
                            <input class="form-control mr-sm-2" type="search" name="question" placeholder="Search">
                            <button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
                        </form>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="container">
            {% block body %}{% endblock body %}
        </div>
    </body>
</html>